version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
  postgres:
    image: "postgres:13.3"
    container_name: povio-assignment-db
    ports:
      - "5432:5432"
    env_file:
      - .env
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      
volumes:
  redis:
    driver: local